version: '3'
services:
  postgres:
    image: postgres:11
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./resources/migrations/20200207094146-add-messages-table.up.sql:/docker-entrypoint-initdb.d/add-messages-table.sql
    environment:
      POSTGRES_PASSWORD: postgres
