version: '3'
services:
# Using artemis, because it exists since 2015!!!
  artemis:
    image: vromero/activemq-artemis:latest-alpine
    ports:
      - 21161:8161  # accessible at http://localhost:21161
      - 21672:5672  # AMQP
      - 21613:61613 # STOMP
      - 21199:1199  # JMX
      - 21198:1198  # RMI
      - 21404:9404
    environment:
      ARTEMIS_USERNAME: artemis
      ARTEMIS_PASSWORD: artemis
      ENABLE_JMX: "true"
      JMX_PORT: 1199
      JMX_RMI_PORT: 1198
      ENABLE_JMX_EXPORTER: "true"
    volumes:
      - ./config:/var/lib/artemis/etc
  # London activemq-cli will send tea production requests
#  london:
