version: '3'
services:
# Using artemis, because it exists since 2015!!!
  artemis:
    image: vromero/activemq-artemis:latest-alpine
    ports:
      - 21161:8161  # accessible at http://localhost:21161
      - 21672:5672  # AMQP
      - 21613:61613 # STOMP
      - 21199:1199  # JMX
      - 21198:1198  # RMI
      - 21404:9404
    environment:
      ARTEMIS_USERNAME: artemis
      ARTEMIS_PASSWORD: artemis
      ENABLE_JMX: "true"
      JMX_PORT: 1199
      JMX_RMI_PORT: 1198
      ENABLE_JMX_EXPORTER: "true"
    volumes:
      - ./activemq:/var/lib/artemis/etc
  # London activemq-cli will send tea production requests
  london:
    build: ./company
    command: python main.py --artemis-host=artemis --artemis-port=61613
    depends_on:
      - srilanka
      - china
      - india
      - artemis
    ports:
        - 21880:8080
  srilanka:
    build: ./producer
    command: python main.py --artemis-host=artemis --artemis-port=61613 --production=7
    depends_on:
      - artemis
    ports:
        - 21881:8080
  china:
    build: ./producer
    command: python main.py --artemis-host=artemis --artemis-port=61613 --name=china --production=55
    depends_on:
      - artemis
    ports:
        - 21882:8080
  india:
    build: ./producer
    command: python main.py --artemis-host=artemis --artemis-port=61613 --name=india --production=32
    depends_on:
      - artemis
    ports:
        - 21883:8080
